name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
env:
  OMP_NUM_THREADS: '10'
  MKL_THREADING_LAYER: GNU
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install clang-format
        run: |
            sudo apt-get update -y
            sudo apt-get install -y wget
            sudo apt install -y lsb-release wget software-properties-common gnupg
            wget https://apt.llvm.org/llvm.sh
            chmod u+x llvm.sh
            sudo ./llvm.sh 18
            sudo apt-get install -y git-core clang-format-18
      - name: Verify clang-format
        run: |
            git ls-files | grep -E  '\.(cpp|h|cu|cuh)$' | xargs clang-format-18 -i
            if git diff --quiet; then
              echo "Formatting OK!"
            else
              echo "Formatting not OK!"
              echo "------------------"
              git --no-pager diff --color
              exit 1
            fi
  linux-x86_64-cmake:
    name: Linux x86_64 (cmake)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build_cmake
  linux-x86_64-GPU-w-ROCm-cmake:
    name: Linux x86_64 GPU w/ ROCm (cmake)
    runs-on: 4-core-ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build_cmake
        with:
          gpu: ON
          rocm: ON
  linux-x86_64-GPU-cmake:
    if: false
    name: Linux x86_64 GPU (cmake)
    needs: linux-x86_64-cmake
    runs-on: 4-core-ubuntu-gpu-t4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build_cmake
        with:
          gpu: ON
  linux-x86_64-GPU-w-RAFT-cmake:
    if: false
    name: Linux x86_64 GPU w/ RAFT (cmake)
    needs: linux-x86_64-cmake
    runs-on: 4-core-ubuntu-gpu-t4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build_cmake
        with:
          gpu: ON
          raft: ON
